### ISSUE TITLE
Protocol not advertised

### ISSUE THREAD

**Issue by UltraBlackLinux** [soreau/wf-kill#1]
Hey there,
I just installed this plugin, and even after a reboot I seem to have trouble using it; I always get the following error: `Wayfire kill view protocol not advertised by compositor. Is wf-kill plugin enabled?`
Why is that? I even tried rebooting, but to no avail.

Now, just out of curiosity, how is [`wf_kill_view_manager`](https://github.com/soreau/wf-kill/blob/53dc6e56c3c4247f3bb6586e0ad6e46b3a111a60/src/client/wf-kill.cpp#L95) being set?

Thanks!

**Comment by soreau** [comment]
As the README states under Runtime, "Enable Wayfire Kill View Protocol plugin 'wf-kill'". You must put `wf-kill` in the list of `[core] plugins` or enable "Wayfire Kill View Protocol" in wcm>Utility category.

**Comment by soreau** [comment]
> Now, just out of curiosity, how is [`wf_kill_view_manager`](https://github.com/soreau/wf-kill/blob/53dc6e56c3c4247f3bb6586e0ad6e46b3a111a60/src/client/wf-kill.cpp#L95) being set?
> 
> Thanks!

The wf-kill client connects to the wayland display socket and sets up a registry handler, then calls roundtrip. This causes the compositor to call the registry handler for each advertised protocol, and wf-kill sets wf_kill_view_manager [here](https://github.com/soreau/wf-kill/blob/master/src/client/wf-kill.cpp#L39).

**Comment by UltraBlackLinux** [comment]
> As the README states under Runtime, "Enable Wayfire Kill View Protocol plugin 'wf-kill'". You must put `wf-kill` in the list of `[core] plugins` or enable "Wayfire Kill View Protocol" in wcm>Utility category.

The problem is that I did enable the plugin. Then I rebooted as it already didn't work.

**Comment by soreau** [comment]
> The problem is that I did enable the plugin. Then I rebooted as it already didn't work.

That's strange, it should work.. can you upload the wayfire log somewhere and post the link here?

**Comment by UltraBlackLinux** [comment]
https://termbin.com/srvn

Oh I see: `EE 08-07-22 09:04:38.510 - [src/output/plugin-loader.cpp:210] Failed to load plugin "wf-kill". Make sure it is installed in /usr/lib/wayfire or in $WAYFIRE_PLUGIN_PATH.`

The installation instructions seem to install this into the wrong directory. It's not in /usr/lib/wayfire and the wayfire plugin path is unset

EDIT: Not even that I suppose. The build directory doesn't have any such so file. Just libwf-info.so

**Comment by soreau** [comment]
I see, I made a typo.. it's fixed now, please pull latest.

**Comment by UltraBlackLinux** [comment]
Works now, love it!

**Comment by soreau** [comment]
Awesome, glad it's working now. You can remove libwf-info.so or install [wf-info](https://github.com/soreau/wf-info) to overwrite it.
