### ISSUE TITLE
Window detection issues

### ISSUE THREAD

**Issue by UltraBlackLinux** [soreau/wf-kill#3]
Hey there,
I'm just now facing some more issues. Suddenly this tool just doesn't do anything other than setting the cursor to a cross and killing the wrong things if it does decide to kill on click.
Let me explain: I have two screens, the left one a bit smaller than the right one. If I now open wf-kill and click on a window on the right screen, nothing appears to happen, even after multiple clicks, but if I then click on the left screen after running wf-kill it just straight up kills wayfire. There are no errors or similars regarding wf-kill.
What is going on here?
Thanks!

**Comment by soreau** [comment]
Does [this patch](http://ix.io/44Kl) help?

**Comment by UltraBlackLinux** [comment]
Appears to be working, thank you!

**Comment by soreau** [comment]
Thanks, I hadn't considered this case.
