### ISSUE TITLE
Add keybind

### ISSUE THREAD

**Issue by UltraBlackLinux** [soreau/wf-kill#4]
Hey there,
I just noticed an issue with this: Some times you don't have the ability to use the cursor to select the window to kill, so a keybind to kill the focused window would be useful (like a more deadly version of the close application keybind)
Could you add this?
Thanks!

**Comment by soreau** [comment]
Sounds like a good idea, but can't you just make a commands plugin binding that calls `wf-kill -t -k`? The `-t` means topmost view and `-k` means send SIGKILL to it.

**Comment by UltraBlackLinux** [comment]
> Sounds like a good idea, but can't you just make a commands plugin binding that calls `wf-kill -t -k`? The `-t` means topmost view and `-k` means send SIGKILL to it.

oh okay, that works. I didn't know that it had cli args. There is no help or manual page for this

**Comment by soreau** [comment]
> oh okay, that works. I didn't know that it had cli args. There is no help or manual page for this

The information is supposed to be in the README, but it doesn't list `-k` yet. Currently, the best documentation is the source.
